zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true
    worker:
      default-name: demo
      default-type: io.camunda.zeebe:userTask



server:
  port: 8080